# Generated by Django 5.1.4 on 2025-01-04 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_hex_color', message='Color must be a valid hexadecimal color code (e.g., #FFFFFF or #FFF).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
    ]
