name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  frontend:
    name: Build and Test Frontend
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci
        working-directory: portfolio

      - name: Run Tests
        run: npm run test
        working-directory: portfolio

      - name: Build Frontend
        run: npm run build
        working-directory: portfolio

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: portfolio/dist

  backend:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    needs: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r portfolioServer/backend/requirements.txt

      - name: Run tests
        working-directory: portfolioServer/backend
        run: |
          python manage.py test

      - name: Collect static files
        working-directory: portfolioServer/backend
        run: |
          python manage.py collectstatic --noinput

      - name: Migrate database
        working-directory: portfolioServer/backend
        run: |
          python manage.py migrate

      - name: Download frontend build artifacts
        uses: actions/download-artifact@v3
        with:
          name: frontend-build